print('Entre com o nome do gato 1: ')
gatonome1 = input()
print('Entre com o nome do gato 2: ')
gatonome2 = input()
print('Entre com o nome do gato 3: ')
gatonome3 = input()
print('Entre com o nome do gato 4: ')
gatonome4 = input()
print('Entre com o nome do gato 5: ')
gatonome5 = input()
print('Entre com o nome do gato 6: ')
gatonome6 = input()

print('O nome dos gatos são: ')
print(gatonome1 + ' ' + gatonome2 + ' ' + gatonome3 +  ' ' + gatonome4 + ' ' + gatonome5 + ' ' + gatonome6)